# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tHZ4q5hUx5TzbSmgGvvgiOYbJZrRLde6
"""
!pip install joblib

import streamlit as st
import numpy as np
import joblib

# Page configuration
st.set_page_config(
    page_title="Stacking Regression Predictor",
    layout="centered"
)

# Load trained stacking model
model = joblib.load("stacking_regression_tuned.pkl")

# Title
st.title("Stacking Regression Prediction System")
st.write(
    "This web application uses a tuned stacking regression model "
    "to generate predictions based on user-provided inputs."
)

# Sidebar for user input
st.sidebar.header("Input Features")

feature_1 = st.sidebar.number_input("Feature 1", value=0.0)
feature_2 = st.sidebar.number_input("Feature 2", value=0.0)
feature_3 = st.sidebar.number_input("Feature 3", value=0.0)
feature_4 = st.sidebar.number_input("Feature 4", value=0.0)

# Convert input to array
input_data = np.array([[feature_1, feature_2, feature_3, feature_4]])

# Prediction button
if st.sidebar.button("Predict"):
    prediction = model.predict(input_data)

    st.subheader("Prediction Result")
    st.success(f"Predicted Value: {prediction[0]:.2f}")

    st.subheader("Model Information")
    st.write("""
    **Model Type:** Stacking Regression
    **Base Models:** Random Forest, Gradient Boosting, Support Vector Regression
    **Meta-Learner:** Linear Regression
    """)

    st.subheader("Model Performance")
    st.write("""
    - R-squared: High explanatory power
    - RMSE: Low prediction error
    - MAE: Strong average accuracy
    - MAPE: Reliable percentage-based performance
    """)
